DirectoryPath: public
CheckDoctype: false # Sadly, this is false only because of `static/google*.html`
TestFilesConcurrently: true
IgnoreAltMissing: true # FIXME
IgnoreDirectoryMissingTrailingSlash: true # FIXME
IgnoreDirs:
  - ^blog/(\d+/)?page/\d+
IgnoreEmptyHref: true # FIXME
IgnoreInternalEmptyHash: true # FIXME
IgnoreInternalURLs: # list of paths
IgnoreURLs: # list of regexs of paths or URLs to be ignored
  - ^https?://localhost\b
  # Ignore Docsy-generated GitHub links for now
  - ^https?://github\.com/.*?/.*?/(new|edit)/ # view-page, edit-source etc
  # Ignore links to GH repo content for now.
  # - ^https?://github\.com/.*?/.*?/(blob|tree)/
  # Sites that deny access, always yielding 401, 403 Forbidden, 406, or other:
  - ^https://(www\.)?linkedin\.com\b # 999 Request Denied
  - ^https://twitter.com
  - ^https://x.com
