# cSpell:ignore github
CacheExpires: 9000h # ~ 12 months
DirectoryPath: public
TestFilesConcurrently: true
IgnoreDirs:
  - ^blog/(\d+/)?page/\d+
IgnoreEmptyHref: true # FIXME
IgnoreInternalEmptyHash: true # FIXME
IgnoreInternalURLs: # list of paths
IgnoreURLs: # Regexes of URLs or paths to be ignored
  - ^https?://localhost
  # Ignore Docsy-generated GitHub links for now
  - ^https?://github\.com/.*?/.*?/(new|edit)/ # view-page, edit-source etc
  # Ignore links to GH repo content for now.
  # - ^https?://github\.com/.*?/.*?/(blob|tree)/
  #
  # Sites that deny access, always yielding 401, 403 Forbidden, 406, or other:
  - ^https://(www\.)?linkedin\.com\b # 999 Request Denied
  - ^https://(x|twitter).com
