name: Links

on:
  merge_group:
  pull_request:
  push: { branches: [main] }

jobs:
  build-and-check-links:
    name: BUILD and CHECK LINKS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm run install:safe

      - run: npm run seq -- check:links _diff:check
